name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Build WordPress Docker Image
        run: docker build -t wordpress-app -f Dockerfile .

      - name: Build MySQL Docker Image
        run: docker build -t mysql-db -f Dockerfile.mysql .

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: List running Docker containers
        run: docker ps

      - name: Wait for WordPress to be ready
        run: |
          for i in {1..10}; do
            if curl --fail http://localhost:8080; then
              echo "WordPress is up!"
              exit 0
            fi
            echo "Waiting for WordPress to be up..."
            sleep 10
          done
          echo "WordPress failed to start in time."
          exit 1

      - name: Verify WordPress Home Page Loads
        run: curl --fail http://localhost:8080 || exit 1

      - name: Print Docker Compose logs (All Containers)
        run: docker-compose logs

      - name: Clean up Docker resources
        run: docker system prune -f
